# Generated by Django 5.1.5 on 2025-01-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(verbose_name='Game_id')),
                ('coef', models.FloatField(verbose_name='Коэффициент')),
                ('player_id', models.FloatField(verbose_name='ID игрока')),
                ('game_type', models.TextField(verbose_name='Тип игры')),
            ],
        ),
    ]
