# Generated by Django 5.1.5 on 2025-02-26 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('casino_profit', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('coef', models.FloatField(verbose_name='Коэффициент')),
                ('player_id', models.TextField(default='-', verbose_name='ID игрока')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Статистика Игр',
                'verbose_name_plural': 'Статистика Игр',
            },
        ),
    ]
