# Generated by Django 5.1.5 on 2025-02-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
