# Generated by Django 5.1.5 on 2025-01-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamestats',
            options={'verbose_name': 'Статистика Игр', 'verbose_name_plural': 'Статистика Игр'},
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='id',
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='game_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='player_id',
            field=models.TextField(default='-', verbose_name='ID игрока'),
        ),
    ]
