# Generated by Django 5.1.5 on 2025-01-23 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0002_alter_gamestats_options_remove_gamestats_game_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestats',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время'),
            preserve_default=False,
        ),
    ]
