# Generated by Django 5.1.5 on 2025-02-26 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0003_gamestats_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('casino_profit', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
