# Generated by Django 5.1.5 on 2025-02-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0003_coefficienthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoefficientHistory',
        ),
    ]
